ls:
  # Regex for dotfiles
  .dir: kebab-case | regex:^\/?(?:\w+\/)*(\.[\w-]+)
  # Regex for dotfiles
  .js: camelCase | kebab-case | regex:^\/?(?:\w+\/)*(\.[\w-]+)
  .jsx: PascalCase
  .config.js: kebab-case
  # Regex for thingsLikeTHISYouKnow (ex: URL, SSG, ...)
  .ts: camelCase | PascalCase | regex:[a-zA-Z]+([A-Za-z]+)+$
  .tsx: PascalCase
  .d.ts: kebab-case
  .stories.tsx: PascalCase
  # Regex for dotfiles
  .yml: kebab-case | regex:^\/?(?:\w+\/)*(\.[\w-]+)
  .md: kebab-case | SCREAMING_SNAKE_CASE
  .json: kebab-case

  apps/web/pages:
    # Regex for _app.tsx
    # Regex for path props (ex: [name].tsx)
    .tsx: kebab-case | regex:_app | regex:\[[a-z]+\]

  packages/web/ui:
    # Regex for dotfiles
    # Regex for config dirs (ex: __stories__)
    .dir: kebab-case | regex:^\/?(?:\w+\/)*(\.[\w-]+) | regex:__[a-zA-Z]+__

  .github:
    .dir: lowercase | SCREAMING_SNAKE_CASE

ignore:
  - .git
  - .husky
  - .idea
  - node_modules
  - apps/web/.next
  - apps/web/node_modules
  - apps/mobile/.expo
  - apps/mobile/node_modules
  - apps/mobile-storybook/node_modules
  - docs/_config.yml
  - packages/api/dist
  - packages/api/node_modules
  - packages/config/eslint/node_modules
  - packages/config/stylelint/node_modules
  - packages/db/node_modules
  - packages/db/prisma/migrations
  - packages/mobile/forms/node_modules
  - packages/mobile/locales/node_modules
  - packages/mobile/storage/node_modules
  - packages/mobile/ui/node_modules
  - packages/theme/node_modules
  - packages/web/forms/node_modules
  - packages/web/locales/node_modules
  - packages/web/storage/node_modules
  - packages/web/ui/node_modules
  - packages/web/ui/storybook-static
  - services/api-gateway/node_modules
  - services/contents/node_modules
  - services/reviews/node_modules
