name: Build Database Package

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
    paths:
      - '.github/workflows/build-packages-db.yml'
      - 'packages/db/**'
      - 'packages/config/eslint/**'
      - 'packages/config/tsconfig/**'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - '.github/workflows/build-packages-db.yml'
      - 'packages/db/**'
      - 'packages/config/eslint/**'
      - 'packages/config/tsconfig/**'

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.9.5

      - name: Install dependencies
        run: pnpm --filter @acme/db install

      - name: Generate prisma client
        run: pnpm --filter @acme/db generate

      - name: Lint
        run: pnpm --filter @acme/db lint

      - name: Build
        run: pnpm --filter @acme/db build
